/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:19:35 GMT 2024
 */

package org.myrobotlab.framework.repo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.framework.repo.Category;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Category_ESTest extends Category_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Category category0 = new Category();
      Category category1 = new Category();
      // Undeclared exception!
      try { 
        category0.compare(category1, category1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.framework.repo.Category", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      String string0 = category0.getSimpleName();
      assertEquals("22vcIi3", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      category0.name = "";
      String string0 = category0.getSimpleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      String string0 = category0.getName();
      assertEquals("22vcIi3", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "";
      String string0 = category0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      int int0 = category0.compare(category0, category0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      Category category1 = new Category();
      category1.name = "22vcIi3";
      category0.name = "2L-";
      int int0 = category0.compare(category0, category1);
      assertEquals(26, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Category category0 = new Category();
      category0.name = "22vcIi3";
      Category category1 = new Category();
      category1.name = "22vcIi3";
      category0.name = "";
      int int0 = category0.compare(category0, category1);
      assertEquals((-7), int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Category category0 = new Category();
      String string0 = category0.getSimpleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Category category0 = new Category();
      String string0 = category0.getName();
      assertNull(string0);
  }
}
