/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:18:51 GMT 2024
 */

package org.myrobotlab.framework.repo;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.framework.repo.ServiceArtifact;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ServiceArtifact_ESTest extends ServiceArtifact_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServiceArtifact serviceArtifact0 = new ServiceArtifact("", (String) null, "");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServiceArtifact serviceArtifact0 = new ServiceArtifact("", "");
  }
}
