/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:55:40 GMT 2024
 */

package org.myrobotlab.kinematics;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.kinematics.Point;
import org.myrobotlab.kinematics.PositionData;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PositionData_ESTest extends PositionData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point point0 = new Point(0.0, 0.0, 0.0);
      PositionData positionData0 = new PositionData("", point0);
  }
}
