/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:59:35 GMT 2024
 */

package org.myrobotlab.codec.json;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;
import org.myrobotlab.codec.json.JsonDeserializationException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JsonDeserializationException_ESTest extends JsonDeserializationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      JsonDeserializationException jsonDeserializationException0 = new JsonDeserializationException(mockThrowable0);
  }
}
