/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:51:33 GMT 2024
 */

package org.myrobotlab.process;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.process.GitHubContent;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GitHubContent_ESTest extends GitHubContent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GitHubContent gitHubContent0 = new GitHubContent();
  }
}
