/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:06:21 GMT 2024
 */

package org.myrobotlab.document.workflow;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.workflow.WorkflowMessage;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WorkflowMessage_ESTest extends WorkflowMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      workflowMessage0.setWorkflow("");
      String string0 = workflowMessage0.getWorkflow();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      workflowMessage0.setType("!-opeXf#S/<;0{Wu");
      String string0 = workflowMessage0.getType();
      assertEquals("!-opeXf#S/<;0{Wu", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      workflowMessage0.setWorkflow("DROP");
      String string0 = workflowMessage0.getWorkflow();
      assertEquals("DROP", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      workflowMessage0.setType("");
      String string0 = workflowMessage0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      String string0 = workflowMessage0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      Document document0 = new Document("");
      workflowMessage0.setDoc(document0);
      Document document1 = workflowMessage0.getDoc();
      assertEquals("", document1.getId());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      Document document0 = workflowMessage0.getDoc();
      assertNull(document0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      WorkflowMessage workflowMessage0 = new WorkflowMessage();
      String string0 = workflowMessage0.getWorkflow();
      assertNull(string0);
  }
}
