/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:21:46 GMT 2024
 */

package org.myrobotlab.roomba;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.roomba.Note;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Note_ESTest extends Note_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Note note0 = new Note(0, (-1591));
      String string0 = note0.toString();
      assertEquals("(0,-1591)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Note note0 = new Note(212, 0);
      int int0 = note0.toSec64ths();
      assertEquals("(212,0)", note0.toString());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Note note0 = new Note(0, (-1591));
      note0.duration = 0;
      note0.duration = 2450;
      int int0 = note0.toSec64ths();
      assertEquals("(0,2450)", note0.toString());
      assertEquals(156, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Note note0 = new Note(0, (-1591));
      int int0 = note0.toSec64ths();
      assertEquals("(0,-1591)", note0.toString());
      assertEquals((-101), int0);
  }
}
