/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Apr 06 03:16:25 GMT 2024
 */

package org.myrobotlab.serial;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class PortStream_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.myrobotlab.serial.PortStream"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/iartes/myrobotlab"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PortStream_ESTest_scaffolding.class.getClassLoader() ,
      "org.myrobotlab.serial.SerialControl",
      "org.myrobotlab.service.interfaces.QueueReporter",
      "org.myrobotlab.framework.QueueStats",
      "org.myrobotlab.framework.interfaces.NameProvider",
      "org.myrobotlab.service.interfaces.SerialDataListener",
      "org.myrobotlab.serial.Port",
      "org.myrobotlab.logging.LoggerFactory",
      "org.myrobotlab.serial.PortStream",
      "org.myrobotlab.service.interfaces.PortListener"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PortStream_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.myrobotlab.logging.LoggerFactory",
      "org.myrobotlab.serial.Port",
      "org.myrobotlab.serial.PortStream",
      "org.myrobotlab.framework.QueueStats",
      "org.myrobotlab.framework.Service",
      "org.myrobotlab.service.IBus",
      "org.myrobotlab.framework.MethodCache",
      "org.myrobotlab.framework.MethodCache$MethodIndex",
      "org.myrobotlab.framework.MethodEntry",
      "org.myrobotlab.service.meta.abstracts.MetaData",
      "org.myrobotlab.service.meta.IBusMeta",
      "org.myrobotlab.service.Lidar",
      "org.myrobotlab.service.meta.LidarMeta",
      "org.myrobotlab.service.Gps",
      "org.myrobotlab.service.meta.GpsMeta",
      "org.myrobotlab.service.TestCatcher",
      "org.myrobotlab.service.meta.TestCatcherMeta",
      "org.myrobotlab.config.ConfigUtils",
      "org.myrobotlab.service.AudioCapture",
      "org.myrobotlab.service.meta.AudioCaptureMeta",
      "org.myrobotlab.service.Relay",
      "org.myrobotlab.service.Serial",
      "org.myrobotlab.serial.PortQueue",
      "org.myrobotlab.service.OculusDiy",
      "org.myrobotlab.service.meta.OculusDiyMeta",
      "org.myrobotlab.service.abstracts.AbstractVideoSink",
      "org.myrobotlab.service.VideoStreamer",
      "org.myrobotlab.service.meta.VideoStreamerMeta"
    );
  }
}
