/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 03:22:10 GMT 2024
 */

package org.myrobotlab.service.interfaces;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.service.interfaces.PinDefinition;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PinDefinition_ESTest extends PinDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 734);
      pinDefinition0.setPin("isDigital ");
      assertEquals("isDigital ", pinDefinition0.getPinName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.setState((-2098));
      Integer integer0 = pinDefinition0.state;
      pinDefinition0.value = integer0;
      pinDefinition0.setState((-1372));
      pinDefinition0.toString();
      assertEquals((-1372), (int)pinDefinition0.getState());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.setState((-2098));
      String string0 = pinDefinition0.toString();
      assertEquals("pin def -1372 -1372 isDigital ", string0);
      assertTrue(pinDefinition0.canRead());
      assertEquals((-2098), (int)pinDefinition0.getState());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.setState((-2098));
      Integer integer0 = pinDefinition0.state;
      assertEquals((-2098), (int)integer0);
      
      pinDefinition0.setPinImpl(integer0);
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isRx());
      assertEquals(0, pinDefinition0.getPollRate());
      assertEquals("-1372", pinDefinition0.getPinName());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
      assertEquals((-1372), (int)pinDefinition0.getAddress());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setPwm(false);
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setDigital(false);
      pinDefinition0.setPwm(true);
      assertTrue(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isDigital());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setDigital(true);
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isEnabled());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setAnalog(false);
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("[b>", 0, "dc(>lQ[PcZjmqd");
      pinDefinition0.setScl(false);
      assertFalse(pinDefinition0.isEnabled());
      assertEquals(0, (int)pinDefinition0.getAddress());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isPwm());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isScl());
      assertEquals("dc(>lQ[PcZjmqd", pinDefinition0.getPinName());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setSda(false);
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setDigital(false);
      pinDefinition0.setSda(true);
      assertFalse(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.isSda());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("0;X:D5mVf0duVq8f`", 0, "0;X:D5mVf0duVq8f`");
      assertFalse(pinDefinition0.isTx());
      
      pinDefinition0.setTx(true);
      boolean boolean0 = pinDefinition0.isTx();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", 275, "");
      assertFalse(pinDefinition0.isSda());
      
      pinDefinition0.setSda(true);
      boolean boolean0 = pinDefinition0.isSda();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      assertFalse(pinDefinition0.isScl());
      
      pinDefinition0.isScl = true;
      boolean boolean0 = pinDefinition0.isScl();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 0, "");
      assertFalse(pinDefinition0.isPwm());
      
      pinDefinition0.setPwm(true);
      boolean boolean0 = pinDefinition0.isPwm();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 0, "");
      assertFalse(pinDefinition0.isEnabled());
      
      pinDefinition0.setEnabled(true);
      boolean boolean0 = pinDefinition0.isEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("x@-", 0);
      assertTrue(pinDefinition0.isDigital());
      
      pinDefinition0.isDigital = false;
      boolean boolean0 = pinDefinition0.isDigital();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 734);
      assertFalse(pinDefinition0.isAnalog());
      
      pinDefinition0.setAnalog(true);
      boolean boolean0 = pinDefinition0.isAnalog();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setValue(0);
      Integer integer0 = pinDefinition0.getValue();
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertEquals(0, (int)integer0);
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.setState((-2098));
      Integer integer0 = pinDefinition0.state;
      pinDefinition0.value = integer0;
      Integer integer1 = pinDefinition0.getValue();
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isRx());
      assertEquals((-1372), (int)pinDefinition0.getAddress());
      assertEquals("-1372", pinDefinition0.getPinName());
      assertFalse(pinDefinition0.isScl());
      assertEquals((-2098), (int)integer1);
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
      assertEquals(0, pinDefinition0.getPollRate());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("2~?^sd|9", 0);
      Integer integer0 = pinDefinition0.address;
      pinDefinition0.state = integer0;
      Integer integer1 = pinDefinition0.getState();
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canWrite());
      assertEquals(0, (int)integer1);
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isScl());
      assertEquals("0", pinDefinition0.getPin());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setState(1415);
      Integer integer0 = pinDefinition0.getState();
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertEquals(1415, (int)integer0);
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.setState((-2098));
      Integer integer0 = pinDefinition0.getState();
      assertFalse(pinDefinition0.isSda());
      assertEquals((-1372), (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertEquals("-1372", pinDefinition0.getPinName());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.canRead());
      assertEquals((-2098), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("isPwm ", 1546);
      pinDefinition0.pollRateHz = 1546;
      int int0 = pinDefinition0.getPollRate();
      assertEquals(1546, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      pinDefinition0.setPollRate((-1907));
      int int0 = pinDefinition0.getPollRate();
      assertEquals((-1907), int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setName(2207);
      String string0 = pinDefinition0.getPinName();
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isPwm());
      assertEquals("2207", string0);
      assertFalse(pinDefinition0.isRx());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", 763);
      assertEquals("763", pinDefinition0.getPin());
      
      pinDefinition0.pin = "";
      pinDefinition0.getPinName();
      assertEquals(763, (int)pinDefinition0.getAddress());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.pinImpl = (Object) "<<,6Z{uO(n=*B[l)av";
      pinDefinition0.getPinImpl();
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.getPin();
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canRead());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", 763);
      assertEquals("763", pinDefinition0.getPinName());
      
      pinDefinition0.pin = "";
      pinDefinition0.getPin();
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setMode("MUrr");
      String string0 = pinDefinition0.getMode();
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertNotNull(string0);
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      pinDefinition0.setMode("");
      String string0 = pinDefinition0.getMode();
      assertEquals("", string0);
      assertFalse(pinDefinition0.isPwm());
      assertEquals((-1907), (int)pinDefinition0.getAddress());
      assertEquals("-1907", pinDefinition0.getPin());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.isDigital());
      assertNotNull(string0);
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canWrite());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", 0, "");
      Integer integer0 = pinDefinition0.getAddress();
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertEquals(0, (int)integer0);
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isEnabled());
      assertNotNull(integer0);
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("[b>", 0, "dc(>lQ[PcZjmqd");
      pinDefinition0.setAddress(1628);
      Integer integer0 = pinDefinition0.getAddress();
      assertEquals(1628, (int)pinDefinition0.getAddress());
      assertNotNull(integer0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("nJeg[eVhpbhWz8(!", (-1), "nJeg[eVhpbhWz8(!");
      Integer integer0 = pinDefinition0.getAddress();
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertNotNull(integer0);
      assertFalse(pinDefinition0.isEnabled());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isRx());
      assertEquals((-1), (int)integer0);
      assertFalse(pinDefinition0.isScl());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("nJeg[eVhpbhWz8(!", (-1), "nJeg[eVhpbhWz8(!");
      assertTrue(pinDefinition0.canWrite());
      
      pinDefinition0.canWrite(false);
      boolean boolean0 = pinDefinition0.canWrite();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      assertTrue(pinDefinition0.canRead());
      
      pinDefinition0.canRead(false);
      boolean boolean0 = pinDefinition0.canRead();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      assertFalse(pinDefinition0.isRx());
      
      pinDefinition0.isRx = true;
      String string0 = pinDefinition0.toString();
      assertEquals("pin def -1372 -1372 isDigital isRx ", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      assertFalse(pinDefinition0.isAnalog());
      
      pinDefinition0.isAnalog = true;
      String string0 = pinDefinition0.toString();
      assertEquals("pin def null null isAnalog isDigital ", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      assertFalse(pinDefinition0.isScl());
      
      pinDefinition0.setScl(true);
      assertTrue(pinDefinition0.isScl());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.canRead(true);
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.isTx();
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isRx());
      assertFalse(boolean0);
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      // Undeclared exception!
      try { 
        pinDefinition0.getState();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.service.interfaces.PinDefinition", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition(";Dy,X=/", (-312), ";Dy,X=/");
      pinDefinition0.setEnabled(false);
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertEquals((-312), (int)pinDefinition0.getAddress());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.isAnalog();
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.canWrite());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(boolean0);
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 0, "");
      boolean boolean0 = pinDefinition0.isEnabled();
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(boolean0);
      assertEquals(0, (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      // Undeclared exception!
      try { 
        pinDefinition0.getValue();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.service.interfaces.PinDefinition", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      assertFalse(pinDefinition0.isTx());
      
      pinDefinition0.setTx(false);
      pinDefinition0.toString();
      assertTrue(pinDefinition0.isTx());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.setValue(844);
      Integer integer0 = pinDefinition0.getValue();
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
      assertEquals(844, (int)integer0);
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      int int0 = pinDefinition0.getPollRate();
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isSda());
      assertEquals("-1907", pinDefinition0.getPinName());
      assertEquals(0, int0);
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isRx());
      assertEquals((-1907), (int)pinDefinition0.getAddress());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.isScl();
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(boolean0);
      assertFalse(pinDefinition0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.canWrite();
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isPwm());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(boolean0);
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isRx());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.getPinName();
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canRead());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      assertFalse(pinDefinition0.isRx());
      
      pinDefinition0.setRx(true);
      boolean boolean0 = pinDefinition0.isRx();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      assertTrue(pinDefinition0.isDigital());
      
      pinDefinition0.setDigital(false);
      pinDefinition0.toString();
      assertFalse(pinDefinition0.isDigital());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.isPwm();
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canWrite());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(boolean0);
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      assertFalse(pinDefinition0.isPwm());
      
      pinDefinition0.setPwm(true);
      pinDefinition0.toString();
      assertTrue(pinDefinition0.isPwm());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      boolean boolean0 = pinDefinition0.isRx();
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(boolean0);
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isTx());
      assertEquals("-1907", pinDefinition0.getPin());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.isDigital());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertEquals((-1907), (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.getAddress();
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertTrue(pinDefinition0.isDigital());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1372));
      pinDefinition0.canWrite(true);
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isSda());
      assertEquals((-1372), (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canRead());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isAnalog());
      assertFalse(pinDefinition0.isTx());
      assertEquals("-1372", pinDefinition0.getPinName());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("x@-", 0);
      boolean boolean0 = pinDefinition0.isDigital();
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
      assertEquals(0, (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isEnabled());
      assertEquals("0", pinDefinition0.getPin());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(boolean0);
      assertEquals(0, pinDefinition0.getPollRate());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isRx());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.canRead();
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isEnabled());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isRx());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isTx());
      assertTrue(boolean0);
      assertFalse(pinDefinition0.isAnalog());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition((String) null, 734);
      pinDefinition0.setPinName("");
      assertEquals("", pinDefinition0.getPin());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      String string0 = pinDefinition0.getPin();
      assertFalse(pinDefinition0.isRx());
      assertEquals(0, pinDefinition0.getPollRate());
      assertEquals("-1907", string0);
      assertFalse(pinDefinition0.isTx());
      assertFalse(pinDefinition0.isPwm());
      assertTrue(pinDefinition0.canWrite());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isSda());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canRead());
      assertEquals((-1907), (int)pinDefinition0.getAddress());
      assertNotNull(string0);
      assertFalse(pinDefinition0.isScl());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition("", (-1907));
      String string0 = pinDefinition0.getMode();
      assertFalse(pinDefinition0.isRx());
      assertNull(string0);
      assertEquals((-1907), (int)pinDefinition0.getAddress());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isTx());
      assertEquals("-1907", pinDefinition0.getPin());
      assertFalse(pinDefinition0.isSda());
      assertEquals(0, pinDefinition0.getPollRate());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isScl());
      assertTrue(pinDefinition0.canRead());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      boolean boolean0 = pinDefinition0.isSda();
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(boolean0);
      assertTrue(pinDefinition0.canWrite());
      assertTrue(pinDefinition0.canRead());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isAnalog());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      PinDefinition pinDefinition0 = new PinDefinition();
      pinDefinition0.getPinImpl();
      assertTrue(pinDefinition0.isDigital());
      assertFalse(pinDefinition0.isPwm());
      assertFalse(pinDefinition0.isScl());
      assertFalse(pinDefinition0.isTx());
      assertTrue(pinDefinition0.canWrite());
      assertFalse(pinDefinition0.isRx());
      assertFalse(pinDefinition0.isEnabled());
      assertFalse(pinDefinition0.isAnalog());
      assertTrue(pinDefinition0.canRead());
      assertEquals(0, pinDefinition0.getPollRate());
      assertFalse(pinDefinition0.isSda());
  }
}
