/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 08 03:24:25 GMT 2024
 */

package org.myrobotlab.service.interfaces;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class VideoProcessWorker_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.myrobotlab.service.interfaces.VideoProcessWorker"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/iartes/myrobotlab"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(VideoProcessWorker_ESTest_scaffolding.class.getClassLoader() ,
      "org.myrobotlab.framework.interfaces.Broadcaster",
      "org.myrobotlab.service.interfaces.QueueReporter",
      "org.myrobotlab.framework.Service",
      "org.myrobotlab.framework.Inbox",
      "org.myrobotlab.framework.interfaces.ServiceQueue",
      "org.myrobotlab.framework.interfaces.MessageSubscriber",
      "org.myrobotlab.framework.interfaces.Invoker",
      "org.myrobotlab.framework.interfaces.MessageInvoker",
      "org.myrobotlab.framework.Status",
      "org.myrobotlab.framework.interfaces.ConfigurableService",
      "org.myrobotlab.framework.MRLListener",
      "org.myrobotlab.framework.interfaces.ServiceStatus",
      "org.myrobotlab.service.config.ServiceConfig",
      "org.myrobotlab.framework.interfaces.NameProvider",
      "org.myrobotlab.framework.interfaces.NameTypeProvider",
      "org.myrobotlab.framework.Message",
      "org.myrobotlab.framework.Peer",
      "org.myrobotlab.framework.interfaces.ServiceInterface",
      "org.myrobotlab.service.interfaces.VideoProcessWorker",
      "org.myrobotlab.framework.interfaces.TaskManager",
      "org.myrobotlab.framework.interfaces.LoggingSink",
      "org.myrobotlab.framework.interfaces.StatusPublisher",
      "org.myrobotlab.service.interfaces.VideoProcessor",
      "org.myrobotlab.framework.interfaces.FutureInvoker",
      "org.myrobotlab.service.meta.abstracts.MetaData",
      "org.myrobotlab.framework.MethodEntry",
      "org.myrobotlab.framework.interfaces.TypeProvider",
      "org.myrobotlab.framework.TimeoutException",
      "org.myrobotlab.framework.interfaces.Attachable",
      "org.myrobotlab.framework.interfaces.StateSaver",
      "org.myrobotlab.framework.interfaces.SimpleMessageSender",
      "org.myrobotlab.framework.interfaces.MessageSender",
      "org.myrobotlab.framework.Outbox",
      "org.myrobotlab.framework.interfaces.StatePublisher"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.lang.ThreadGroup", false, VideoProcessWorker_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.myrobotlab.service.interfaces.VideoProcessor", false, VideoProcessWorker_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(VideoProcessWorker_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.myrobotlab.service.interfaces.VideoProcessWorker"
    );
  }
}
