/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:29:30 GMT 2024
 */

package org.saintandreas.gl.buffers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.saintandreas.gl.buffers.VertexBuffer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VertexBuffer_ESTest extends VertexBuffer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        VertexBuffer.unbind();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/lwjgl/opengl/GL15
         //
         verifyException("org.saintandreas.gl.buffers.BaseBuffer", e);
      }
  }
}
