/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:45:54 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.transformer.ConnectorConfig;
import org.myrobotlab.document.transformer.StageConfiguration;
import org.myrobotlab.document.transformer.WorkflowConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Configuration_ESTest extends Configuration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String string0 = workflowConfiguration0.getStringParam("org.myrobotlab.document.transformer.AbstractStage", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      String string0 = workflowConfiguration0.getStringParam("org.myrobotlab.document.transformer.Configuration");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration("|jkFw(8|eh", "|jkFw(8|eh");
      stageConfiguration0.setStringParam("|jkFw(8|eh", "");
      String string0 = stageConfiguration0.getStringParam("|jkFw(8|eh");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration("", "9GIP9i.q~W7Ap)");
      String[] stringArray0 = new String[1];
      stageConfiguration0.setStringArray("", stringArray0);
      String[] stringArray1 = stageConfiguration0.getStringArray("");
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      String string0 = stageConfiguration0.getProperty("F5`r`X1ETa", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ConnectorConfig connectorConfig0 = new ConnectorConfig("", "");
      String string0 = connectorConfig0.getProperty("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration("", "ZUm[VQ+:U<njh");
      stageConfiguration0.setStringParam("", "Ln{YD");
      String string0 = stageConfiguration0.getProperty("");
      assertEquals("Ln{YD", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration("", "9GIP9i.q~W7Ap)");
      stageConfiguration0.setStringParam("", "");
      String string0 = stageConfiguration0.getProperty("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("$");
      HashMap<Object, Boolean> hashMap0 = new HashMap<Object, Boolean>();
      workflowConfiguration0.setMapProperty("$", hashMap0);
      Map<String, String> map0 = workflowConfiguration0.getMapProperty("$");
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("$");
      Boolean boolean0 = Boolean.valueOf(true);
      HashMap<Object, Boolean> hashMap0 = new HashMap<Object, Boolean>();
      hashMap0.put(boolean0, boolean0);
      workflowConfiguration0.setMapProperty("$", hashMap0);
      Map<String, String> map0 = workflowConfiguration0.getMapProperty("$");
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("");
      workflowConfiguration0.setListParam("", arrayList0);
      List<String> list0 = workflowConfiguration0.getListParam("");
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration(">uB5.b\"RX)?}6I", "!h%$G@3whbj");
      Integer integer0 = new Integer(0);
      Integer integer1 = stageConfiguration0.getIntegerParam("!h%$G@3whbj", integer0);
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      Integer integer0 = Integer.getInteger("OdzWH@++ sv1G|", 1959);
      Integer integer1 = stageConfiguration0.getIntegerParam("", integer0);
      assertEquals(1959, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      Boolean boolean0 = workflowConfiguration0.getBoolParam("", (Boolean) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.setStringParam("SSE4+Su+d}V/", "SSE4+Su+d}V/");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      String[] stringArray0 = new String[5];
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.setStringArray("", stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.setMapProperty((String) null, (Map) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      workflowConfiguration0.config = null;
      ArrayList<String> arrayList0 = new ArrayList<String>();
      // Undeclared exception!
      try { 
        workflowConfiguration0.setListParam("org.myrobotlab.document.transformer.Configuration", arrayList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.setIntegerParam((String) null, (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      Boolean boolean0 = Boolean.valueOf(true);
      // Undeclared exception!
      try { 
        workflowConfiguration0.setBoolParam("java.lang.Long", boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.getStringParam("<cR2}f#F");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration(">9~7g39X7G2n ");
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.getStringArray(">9~7g39X7G2n ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ConnectorConfig connectorConfig0 = new ConnectorConfig(">,", ">,");
      connectorConfig0.setStringArray("jC", (String[]) null);
      // Undeclared exception!
      try { 
        connectorConfig0.getProperty("jC", "e3N?4?mLnC6ud6");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.setListParam("|%<*Jp'K/Ht", (List<String>) null);
      // Undeclared exception!
      try { 
        workflowConfiguration0.getProperty("|%<*Jp'K/Ht");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.getMapProperty("['$O~|5u]n7H4\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.setStringParam("PHZiwRZj.^wV(zlx1", "PHZiwRZj.^wV(zlx1");
      // Undeclared exception!
      try { 
        stageConfiguration0.getMapProperty("PHZiwRZj.^wV(zlx1");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("");
      workflowConfiguration0.config = null;
      // Undeclared exception!
      try { 
        workflowConfiguration0.getListParam("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.setListParam("", (List<String>) null);
      // Undeclared exception!
      try { 
        stageConfiguration0.getStringParam("", "((");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String string0 = workflowConfiguration0.getStringParam("", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("V;)jg0d.wC5");
      ArrayList<String> arrayList0 = new ArrayList<String>();
      workflowConfiguration0.setListParam("V;)jg0d.wC5", arrayList0);
      List<String> list0 = workflowConfiguration0.getListParam("V;)jg0d.wC5");
      assertFalse(list0.contains("V;)jg0d.wC5"));
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("$");
      List<String> list0 = workflowConfiguration0.getListParam("nb,#_");
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String[] stringArray0 = new String[0];
      workflowConfiguration0.setStringArray("org.myrobotlab.document.transformer.Configuration", stringArray0);
      String[] stringArray1 = workflowConfiguration0.getStringArray("org.myrobotlab.document.transformer.Configuration");
      assertSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("$");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      workflowConfiguration0.setListParam("", linkedList0);
      String[] stringArray0 = workflowConfiguration0.getStringArray("");
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("$");
      String[] stringArray0 = workflowConfiguration0.getStringArray("$");
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.setStringParam((String) null, (String) null);
      Boolean boolean0 = Boolean.valueOf((String) null);
      // Undeclared exception!
      try { 
        stageConfiguration0.getBoolParam((String) null, boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      Boolean boolean0 = Boolean.valueOf("");
      stageConfiguration0.setBoolParam(">TOCLybva", boolean0);
      Boolean boolean1 = stageConfiguration0.getBoolParam(">TOCLybva", boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(true);
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      Boolean boolean1 = workflowConfiguration0.getBoolParam("", boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      Integer integer0 = new Integer((-2210));
      stageConfiguration0.setIntegerParam("Constructor for type threw an exception", integer0);
      Integer integer1 = stageConfiguration0.getIntegerParam("Constructor for type threw an exception", integer0);
      assertEquals((-2210), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      Integer integer0 = workflowConfiguration0.getIntegerParam("com.thoughtworks.xstream.core.JVM$Test", (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String string0 = workflowConfiguration0.getProperty("r~E4_&W4<", "r~E4_&W4<");
      assertEquals("r~E4_&W4<", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      Boolean boolean0 = Boolean.valueOf("");
      stageConfiguration0.setBoolParam(">TOCLybva", boolean0);
      String string0 = stageConfiguration0.getProperty(">TOCLybva", ">TOCLybva");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ConnectorConfig connectorConfig0 = new ConnectorConfig("A/PTt{@24/t?6", "A/PTt{@24/t?6");
      connectorConfig0.setStringParam("A/PTt{@24/t?6", "org.myrobotlab.document.transformer.Configuration");
      String string0 = connectorConfig0.getStringParam("A/PTt{@24/t?6", "A/PTt{@24/t?6");
      assertEquals("org.myrobotlab.document.transformer.Configuration", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration("V;)jg0d.wC5");
      ArrayList<String> arrayList0 = new ArrayList<String>();
      workflowConfiguration0.setListParam("V;)jg0d.wC5", arrayList0);
      String string0 = workflowConfiguration0.getStringParam("V;)jg0d.wC5");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String string0 = workflowConfiguration0.toXML();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      String string0 = workflowConfiguration0.getProperty("|%<*Jp'K/Ht");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      HashMap<Boolean, Object> hashMap0 = new HashMap<Boolean, Object>();
      workflowConfiguration0.setMapProperty("", hashMap0);
      // Undeclared exception!
      try { 
        workflowConfiguration0.getIntegerParam("", (Integer) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"java.util.HashMap@0000000002\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      Map<String, String> map0 = workflowConfiguration0.getMapProperty("['$O~|5u]n7H4\"");
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      WorkflowConfiguration workflowConfiguration0 = new WorkflowConfiguration();
      workflowConfiguration0.setStringParam((String) null, (String) null);
      Integer integer0 = new Integer(1);
      // Undeclared exception!
      try { 
        workflowConfiguration0.getIntegerParam((String) null, integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }
}
