/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:44:40 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.transformer.CopyField;
import org.myrobotlab.document.transformer.StageConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CopyField_ESTest extends CopyField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.config = null;
      // Undeclared exception!
      try { 
        copyField0.startStage(stageConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.StageConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      // Undeclared exception!
      try { 
        copyField0.processDocument((Document) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.CopyField", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = new Document("");
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      arrayList0.add((Object) document0);
      document0.setField("fielda", arrayList0);
      CopyField copyField0 = new CopyField();
      List<Document> list0 = copyField0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      Document document0 = new Document("");
      List<Document> list0 = copyField0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      copyField0.startStage(stageConfiguration0);
      assertEquals("defaultStage", stageConfiguration0.getStageName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      copyField0.startStage((StageConfiguration) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      copyField0.stopStage();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CopyField copyField0 = new CopyField();
      copyField0.flush();
  }
}
