/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:29:02 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.transformer.DictionaryLoader;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DictionaryLoader_ESTest extends DictionaryLoader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DictionaryLoader dictionaryLoader0 = new DictionaryLoader();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DictionaryLoader dictionaryLoader0 = DictionaryLoader.getInstance();
      // Undeclared exception!
      try { 
        dictionaryLoader0.loadDictionary((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DictionaryLoader dictionaryLoader0 = DictionaryLoader.getInstance();
      HashMap<String, List<String>> hashMap0 = dictionaryLoader0.loadDictionary("Qkc%f");
      assertNull(hashMap0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DictionaryLoader dictionaryLoader0 = DictionaryLoader.getInstance();
      // Undeclared exception!
      try { 
        dictionaryLoader0.loadDictionary("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // au/com/bytecode/opencsv/CSVReader
         //
         verifyException("org.myrobotlab.document.transformer.DictionaryLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DictionaryLoader dictionaryLoader0 = DictionaryLoader.getInstance();
      DictionaryLoader dictionaryLoader1 = DictionaryLoader.getInstance();
      assertSame(dictionaryLoader1, dictionaryLoader0);
  }
}
