/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:49:16 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.transformer.JSoupExtractor;
import org.myrobotlab.document.transformer.StageConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JSoupExtractor_ESTest extends JSoupExtractor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      
      jSoupExtractor0.setjSoupSelector((String) null);
      jSoupExtractor0.getjSoupSelector();
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      
      jSoupExtractor0.setjSoupSelector("");
      jSoupExtractor0.getjSoupSelector();
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("links", jSoupExtractor0.getOutputField());
      
      jSoupExtractor0.setOutputField((String) null);
      jSoupExtractor0.getOutputField();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("links", jSoupExtractor0.getOutputField());
      
      jSoupExtractor0.setOutputField("");
      jSoupExtractor0.getOutputField();
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("html", jSoupExtractor0.getHtmlField());
      
      jSoupExtractor0.setHtmlField("");
      jSoupExtractor0.getHtmlField();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.setIntegerParam("jSoupSelector", (Integer) null);
      // Undeclared exception!
      try { 
        jSoupExtractor0.startStage(stageConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      // Undeclared exception!
      try { 
        jSoupExtractor0.processDocument((Document) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.JSoupExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("html", jSoupExtractor0.getHtmlField());
      
      Document document0 = new Document(";");
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      document0.setField(";", arrayList0);
      jSoupExtractor0.setHtmlField(";");
      jSoupExtractor0.processDocument(document0);
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      Document document0 = new Document("Tey<% Wj6{:(\"");
      document0.setField("Tey<% Wj6{:(\"", (Object) jSoupExtractor0);
      jSoupExtractor0.setHtmlField("Tey<% Wj6{:(\"");
      // Undeclared exception!
      try { 
        jSoupExtractor0.processDocument(document0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jsoup/Jsoup
         //
         verifyException("org.myrobotlab.document.transformer.JSoupExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      jSoupExtractor0.startStage(stageConfiguration0);
      assertEquals("html", jSoupExtractor0.getHtmlField());
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      jSoupExtractor0.startStage((StageConfiguration) null);
      assertEquals("html", jSoupExtractor0.getHtmlField());
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      String string0 = jSoupExtractor0.getHtmlField();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("html", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      String string0 = jSoupExtractor0.getOutputField();
      assertEquals("html", jSoupExtractor0.getHtmlField());
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("links", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      String string0 = jSoupExtractor0.getjSoupSelector();
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("a[href]", string0);
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      jSoupExtractor0.flush();
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      assertEquals("html", jSoupExtractor0.getHtmlField());
      
      jSoupExtractor0.setHtmlField((String) null);
      jSoupExtractor0.getHtmlField();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("links", jSoupExtractor0.getOutputField());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JSoupExtractor jSoupExtractor0 = new JSoupExtractor();
      jSoupExtractor0.stopStage();
      assertEquals("a[href]", jSoupExtractor0.getjSoupSelector());
      assertEquals("links", jSoupExtractor0.getOutputField());
      assertEquals("html", jSoupExtractor0.getHtmlField());
  }
}
