/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:42:26 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.transformer.ParseDate;
import org.myrobotlab.document.transformer.StageConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ParseDate_ESTest extends ParseDate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("formatStrings");
      StageConfiguration stageConfiguration0 = new StageConfiguration("formatStrings", "formatStrings");
      stageConfiguration0.setListParam("formatStrings", arrayList0);
      // Undeclared exception!
      try { 
        parseDate0.startStage(stageConfiguration0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal pattern character 'f'
         //
         verifyException("java.text.SimpleDateFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      Document document0 = new Document("jaba.ti=e.chronocHijrahChrnol#gy");
      document0.addToField("jaba.ti=e.chronocHijrahChrnol#gy", "jaba.ti=e.chronocHijrahChrnol#gy");
      document0.renameField("jaba.ti=e.chronocHijrahChrnol#gy", (String) null);
      // Undeclared exception!
      try { 
        parseDate0.processDocument(document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.ParseDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      Document document0 = new Document("x_F-04wXwDH<]D4`");
      List<Document> list0 = parseDate0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      Document document0 = new Document("jaba.ti=e.chronocHijrahChrnol#gy");
      document0.addToField("jaba.ti=e.chronocHijrahChrnol#gy", parseDate0);
      document0.renameField("jaba.ti=e.chronocHijrahChrnol#gy", (String) null);
      // Undeclared exception!
      try { 
        parseDate0.processDocument(document0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("");
      StageConfiguration stageConfiguration0 = new StageConfiguration("com.thoughtworks.xstream.core.util.FastField", "inputField");
      stageConfiguration0.setListParam("formatStrings", arrayList0);
      parseDate0.startStage(stageConfiguration0);
      assertEquals("com.thoughtworks.xstream.core.util.FastField", stageConfiguration0.getStageName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      StageConfiguration stageConfiguration0 = new StageConfiguration("com.thoughtworks.xstream.core.util.FastField", "inputField");
      // Undeclared exception!
      try { 
        parseDate0.startStage(stageConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.ParseDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      // Undeclared exception!
      try { 
        parseDate0.startStage((StageConfiguration) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.ParseDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      parseDate0.flush();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ParseDate parseDate0 = new ParseDate();
      parseDate0.stopStage();
  }
}
