/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:30:07 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.transformer.RenameField;
import org.myrobotlab.document.transformer.StageConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RenameField_ESTest extends RenameField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      stageConfiguration0.config = null;
      // Undeclared exception!
      try { 
        renameField0.startStage(stageConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.StageConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      // Undeclared exception!
      try { 
        renameField0.processDocument((Document) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.RenameField", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      Document document0 = new Document("fielda");
      document0.setField("fielda", (Object) "fielda");
      List<Document> list0 = renameField0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      Document document0 = new Document("_e8g");
      List<Document> list0 = renameField0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      renameField0.startStage(stageConfiguration0);
      assertEquals("defaultStage", stageConfiguration0.getStageName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      renameField0.startStage((StageConfiguration) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      renameField0.stopStage();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RenameField renameField0 = new RenameField();
      renameField0.flush();
  }
}
