/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:43:32 GMT 2024
 */

package org.myrobotlab.document.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.document.Document;
import org.myrobotlab.document.transformer.StageConfiguration;
import org.myrobotlab.document.transformer.SumValues;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SumValues_ESTest extends SumValues_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      StageConfiguration stageConfiguration0 = new StageConfiguration("p HJ", "p HJ");
      stageConfiguration0.config = null;
      // Undeclared exception!
      try { 
        sumValues0.startStage(stageConfiguration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      // Undeclared exception!
      try { 
        sumValues0.processDocument((Document) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.document.transformer.SumValues", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      List<String> list0 = List.of();
      stageConfiguration0.setListParam("inputFields", list0);
      sumValues0.startStage(stageConfiguration0);
      Document document0 = new Document("inputFields");
      // Undeclared exception!
      try { 
        sumValues0.processDocument(document0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("inputFields");
      stageConfiguration0.setListParam("inputFields", arrayList0);
      sumValues0.startStage(stageConfiguration0);
      Document document0 = new Document("inputFields");
      document0.addToField("inputFields", "inputFields");
      List<Document> list0 = sumValues0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      stageConfiguration0.setListParam("inputFields", arrayList0);
      sumValues0.startStage(stageConfiguration0);
      Document document0 = new Document("inputFields");
      // Undeclared exception!
      try { 
        sumValues0.processDocument(document0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      StageConfiguration stageConfiguration0 = new StageConfiguration();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("inputFields");
      stageConfiguration0.setListParam("inputFields", arrayList0);
      sumValues0.startStage(stageConfiguration0);
      Document document0 = new Document("inputFields");
      List<Document> list0 = sumValues0.processDocument(document0);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      sumValues0.startStage((StageConfiguration) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      sumValues0.flush();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SumValues sumValues0 = new SumValues();
      sumValues0.stopStage();
  }
}
