/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:30:14 GMT 2024
 */

package org.myrobotlab.framework;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.framework.Instantiator;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Instantiator_ESTest extends Instantiator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object[] objectArray0 = new Object[7];
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 6);
      Object object0 = Instantiator.getNewInstance(classArray0, "KBQ=#k}R~Q", objectArray0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Object[] objectArray0 = new Object[5];
      Object object0 = Instantiator.getNewInstance("@!X2s2`Y", objectArray0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object object0 = Instantiator.getNewInstance(":FMJNt+A~RCCHR*v4e");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Object object0 = Instantiator.getNewInstance(class0, "org.myrobotlab.framework.Instantiator", (Object[]) null);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Instantiator instantiator0 = new Instantiator();
      // Undeclared exception!
      try { 
        Instantiator.invoke(instantiator0, (String) null, classArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 1);
      Object[] objectArray0 = new Object[0];
      try { 
        Instantiator.getThrowableNewInstance(classArray0, "org.myrobotlab.framework.Instantiator", objectArray0);
        fail("Expecting exception: NoSuchMethodException");
      
      } catch(NoSuchMethodException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 1);
      try { 
        Instantiator.getThrowableNewInstance(classArray0, "Mw0;d", classArray0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object object0 = Instantiator.getThrowableNewInstance((Class<?>[]) null, "org.myrobotlab.logging.LoggerFactory", classArray0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 4);
      Object object0 = Instantiator.getThrowableNewInstance(classArray0, "org.myrobotlab.framework.Instantiator", (Object[]) null);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object object0 = Instantiator.getNewInstance((Class<?>[]) classArray0, "org.myrobotlab.framework.Instantiator", (Object[]) classArray0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) "og.mykobot|ab.>ramework.Ins$ntiator";
      try { 
        Instantiator.invoke("og.mykobot|ab.>ramework.Ins$ntiator", "og.mykobot|ab.>ramework.Ins$ntiator", objectArray0);
        fail("Expecting exception: NoSuchMethodException");
      
      } catch(NoSuchMethodException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 5);
      try { 
        Instantiator.invoke("org.myrobotlab.framework.Instantiator", "org.myrobotlab.framework.Instantiator", classArray0);
        fail("Expecting exception: NoSuchMethodException");
      
      } catch(NoSuchMethodException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object object0 = Instantiator.invoke((Object) null, (String) null, classArray0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      try { 
        Instantiator.invoke("org.myrobotlab.framework.Instantiator", "org.myrobotlab.framework.Instantiator", (Object[]) null);
        fail("Expecting exception: NoSuchMethodException");
      
      } catch(NoSuchMethodException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) "org.myrobotlab.logging.LoggerFactory";
      try { 
        Instantiator.getThrowableNewInstance(classArray0, "org.myrobotlab.logging.LoggerFactory", objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object[] objectArray0 = new Object[1];
      // Undeclared exception!
      try { 
        Instantiator.getThrowableNewInstance(classArray0, "org.myrobotlab.logging.LoggerFactory", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.framework.Instantiator", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 1);
      Class<Instantiator> class0 = Instantiator.class;
      Object object0 = Instantiator.getNewInstance((Class<?>) class0, "#*FANmx|\">2: me>P", (Object[]) classArray0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Object object0 = Instantiator.getNewInstance("org.myrobotlab.framework.Instantiator");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      Object object0 = Instantiator.getNewInstance("org.myrobotlab.framework.Instantiator", (Object[]) classArray0);
      assertNotNull(object0);
  }
}
