/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:18:15 GMT 2024
 */

package org.myrobotlab.framework;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.framework.QueueStats;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class QueueStats_ESTest extends QueueStats_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QueueStats queueStats0 = new QueueStats();
      queueStats0.name = "bP^^nB";
      String string0 = queueStats0.getName();
      assertEquals("bP^^nB", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QueueStats queueStats0 = new QueueStats();
      queueStats0.name = "bP^^nB";
      queueStats0.name = "";
      String string0 = queueStats0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      QueueStats queueStats0 = new QueueStats();
      String string0 = queueStats0.getName();
      assertNull(string0);
  }
}
