/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:29:06 GMT 2024
 */

package org.myrobotlab.framework;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.framework.RoutingEntry;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RoutingEntry_ESTest extends RoutingEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RoutingEntry routingEntry0 = new RoutingEntry();
      RoutingEntry routingEntry1 = new RoutingEntry(routingEntry0);
      assertEquals(0, routingEntry1.ID);
      assertEquals(1392409281320L, routingEntry1.timestamp);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RoutingEntry routingEntry0 = new RoutingEntry();
      // Undeclared exception!
      try { 
        routingEntry0.set((RoutingEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.framework.RoutingEntry", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RoutingEntry routingEntry0 = new RoutingEntry();
      routingEntry0.set(routingEntry0);
      assertEquals(0, routingEntry0.ID);
      assertEquals(1392409281320L, routingEntry0.timestamp);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RoutingEntry routingEntry0 = new RoutingEntry();
      String string0 = routingEntry0.toString();
      assertEquals("{\"ID\":\"0\"\"name\":\"\"\"timestamp\":\"1392409281320\"}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RoutingEntry routingEntry0 = null;
      try {
        routingEntry0 = new RoutingEntry((RoutingEntry) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.framework.RoutingEntry", e);
      }
  }
}
