/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:32:47 GMT 2024
 */

package org.saintandreas.gl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.saintandreas.gl.IndexedGeometry;
import org.saintandreas.gl.buffers.IndexBuffer;
import org.saintandreas.gl.buffers.VertexArray;
import org.saintandreas.gl.buffers.VertexBuffer;
import org.saintandreas.math.Vector4f;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IndexedGeometry_ESTest extends IndexedGeometry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IndexedGeometry indexedGeometry0 = new IndexedGeometry((IndexBuffer) null, (VertexBuffer) null, (VertexArray) null, (-729), 0);
      // Undeclared exception!
      try { 
        indexedGeometry0.draw();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/lwjgl/opengl/GL11
         //
         verifyException("org.saintandreas.gl.IndexedGeometry", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IndexedGeometry indexedGeometry0 = new IndexedGeometry((IndexBuffer) null, (VertexBuffer) null, (VertexArray) null, (-1514), (-1514));
      // Undeclared exception!
      try { 
        indexedGeometry0.destroy();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.gl.Geometry", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IndexedGeometry indexedGeometry0 = new IndexedGeometry((IndexBuffer) null, (VertexBuffer) null, (VertexArray) null, (-1514), (-1514));
      // Undeclared exception!
      try { 
        indexedGeometry0.bindVertexArray();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.gl.Geometry", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IndexedGeometry.Builder indexedGeometry_Builder0 = new IndexedGeometry.Builder((IndexBuffer) null, (VertexBuffer) null, 0);
      // Undeclared exception!
      try { 
        indexedGeometry_Builder0.build();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/lwjgl/opengl/GL30
         //
         verifyException("org.saintandreas.gl.buffers.VertexArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IndexedGeometry.Builder indexedGeometry_Builder0 = new IndexedGeometry.Builder((IndexBuffer) null, (VertexBuffer) null, (-1500));
      // Undeclared exception!
      try { 
        indexedGeometry_Builder0.buildVertexArray();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/lwjgl/opengl/GL30
         //
         verifyException("org.saintandreas.gl.buffers.VertexArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<Integer> list0 = List.of();
      LinkedList<Vector4f> linkedList0 = new LinkedList<Vector4f>();
      IndexedGeometry.Builder indexedGeometry_Builder0 = null;
      try {
        indexedGeometry_Builder0 = new IndexedGeometry.Builder(list0, linkedList0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/saintandreas/resources/Resource
         //
         verifyException("org.saintandreas.gl.IndexedGeometry$Builder", e);
      }
  }
}
