/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 03:15:13 GMT 2024
 */

package org.myrobotlab.arduino.virtual;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.arduino.virtual.HardwareSerial;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HardwareSerial_ESTest extends HardwareSerial_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      hardwareSerial0.begin((-1108));
      assertFalse(hardwareSerial0.available());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      int int0 = hardwareSerial0.read();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      boolean boolean0 = hardwareSerial0.available();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      int[] intArray0 = new int[3];
      hardwareSerial0.write(intArray0, (-3925));
      assertFalse(hardwareSerial0.ready());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      hardwareSerial0.write(567, (-3925));
      assertFalse(hardwareSerial0.available());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      hardwareSerial0.flush();
      assertFalse(hardwareSerial0.ready());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HardwareSerial hardwareSerial0 = new HardwareSerial();
      boolean boolean0 = hardwareSerial0.ready();
      assertFalse(boolean0);
  }
}
