/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 03:16:22 GMT 2024
 */

package org.myrobotlab.arduino.virtual;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.arduino.virtual.HardwareMotor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HardwareMotor_ESTest extends HardwareMotor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HardwareMotor hardwareMotor0 = new HardwareMotor();
      hardwareMotor0.moveTo(1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HardwareMotor hardwareMotor0 = new HardwareMotor();
      hardwareMotor0.move(0);
  }
}
