/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 03:04:01 GMT 2024
 */

package org.myrobotlab.arduino.virtual;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.arduino.virtual.ListNode;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ListNode_ESTest extends ListNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ListNode<Integer> listNode0 = new ListNode<Integer>();
  }
}
