/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:42:44 GMT 2024
 */

package org.myrobotlab.math.geometry;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.math.geometry.Line3df;
import org.myrobotlab.math.geometry.Point3df;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Line3df_ESTest extends Line3df_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point3df point3df0 = new Point3df((-690.6464F), 0.0F, 0.0F);
      Point3df point3df1 = new Point3df();
      Line3df line3df0 = new Line3df(point3df0, point3df1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Line3df line3df0 = new Line3df(5186.0F, 5186.0F, 5186.0F, (-2727.0F), 1454.3F, 1454.3F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Line3df line3df0 = new Line3df((-1026.0358F), (-1072.6776F), 0.0F, (-1072.6776F), (-1072.6776F), 0.0F);
      String string0 = line3df0.toString();
      assertEquals("((-1026.035767,-1072.677612,0.0),(-1072.677612,-1072.677612,0.0))", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Line3df line3df0 = new Line3df();
      String string0 = line3df0.toString();
      assertEquals("(null,null)", string0);
  }
}
