/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 01:43:53 GMT 2024
 */

package org.myrobotlab.math.geometry;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.math.geometry.Point;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Point_ESTest extends Point_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point point0 = new Point(1, 1);
      String string0 = point0.toString();
      assertEquals("(1,1)", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Point point0 = new Point((-932), (-932), (-1));
      assertEquals((-932), point0.y);
      assertEquals((-932), point0.x);
      assertEquals((-1), point0.value);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Point point0 = new Point(2, 701, 701);
      assertEquals(2, point0.x);
      assertEquals(701, point0.value);
      assertEquals(701, point0.y);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Point point0 = new Point(0, 169);
      assertEquals(0, point0.x);
      assertEquals(169, point0.y);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Point point0 = new Point(1, 1);
      assertEquals(1, point0.x);
      
      point0.x = 0;
      String string0 = point0.toString();
      assertEquals("(0,1)", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Point point0 = new Point();
      String string0 = point0.toString();
      assertEquals("(0,0)", string0);
  }
}
