/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:57:09 GMT 2024
 */

package org.myrobotlab.image;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.image.BufferedImage;
import java.awt.image.RasterFormatException;
import java.awt.image.RenderedImage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.image.Convert;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Convert_ESTest extends Convert_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      BufferedImage bufferedImage0 = Convert.toImage(2, 1, byteArray0);
      assertEquals(0, bufferedImage0.getType());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(868, 1, 3);
      BufferedImage bufferedImage1 = Convert.convertRenderedImage(bufferedImage0);
      assertSame(bufferedImage1, bufferedImage0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(1, 1, 1);
      BufferedImage bufferedImage1 = Convert.convertRenderedImage(bufferedImage0);
      assertSame(bufferedImage1, bufferedImage0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      BufferedImage bufferedImage0 = Convert.toImage(1, 1, byteArray0);
      bufferedImage0.setAccelerationPriority((byte)0);
      BufferedImage bufferedImage1 = Convert.convertRenderedImage(bufferedImage0);
      assertEquals(0, bufferedImage1.getType());
      assertEquals(0.0F, bufferedImage1.getAccelerationPriority(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        Convert.toImage(521, 521, (byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        Convert.toImage((-1282), (-1282), (byte[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width (-1282) and height (-1282) must be > 0
         //
         verifyException("java.awt.image.SampleModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      // Undeclared exception!
      try { 
        Convert.toImage(5, 5, byteArray0);
        fail("Expecting exception: RasterFormatException");
      
      } catch(RasterFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        Convert.convertRenderedImage((RenderedImage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.myrobotlab.image.Convert", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      BufferedImage bufferedImage0 = Convert.toImage((byte)1, (byte)3, byteArray0);
      BufferedImage bufferedImage1 = Convert.convertRenderedImage(bufferedImage0);
      assertEquals(0, bufferedImage1.getType());
      assertEquals(3, bufferedImage1.getTileHeight());
      assertSame(bufferedImage1, bufferedImage0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Convert convert0 = new Convert();
  }
}
