/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:39:38 GMT 2024
 */

package org.saintandreas.math;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.saintandreas.math.Quaternion;
import org.saintandreas.math.Vector2f;
import org.saintandreas.math.Vector3f;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Vector3f_ESTest extends Vector3f_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Quaternion quaternion0 = Quaternion.fromMatrix3f(0.0F, -0.0F, 2324.6F, (-1657.2854F), 65504.0F, -0.0F, 0.0F, Float.NaN, (-1221.8F));
      Vector3f vector3f0 = quaternion0.getRotationColumn(2);
      float float0 = vector3f0.get(2);
      assertEquals("(NaN, NaN, NaN)", vector3f0.toString());
      assertEquals(Float.NaN, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(3305.94F);
      float float0 = vector3f0.UNIT_X.get(0);
      assertEquals(1.0F, float0, 0.01F);
      assertEquals(3305.94F, vector3f0.y, 0.01F);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(-0.0F);
      Vector3f vector3f1 = Vector3f.UNIT_Y;
      Vector3f vector3f2 = vector3f1.UNIT_Y.max(vector3f0);
      Vector3f vector3f3 = vector3f1.UNIT_Z.add(vector3f2);
      boolean boolean0 = vector3f3.equals(vector3f1);
      assertTrue(vector3f2.equals((Object)vector3f1));
      assertEquals("(0.0, 1.0, 1.0)", vector3f3.toString());
      assertEquals(-0.0F, vector3f0.y, 0.01F);
      assertFalse(boolean0);
      assertFalse(vector3f2.equals((Object)vector3f3));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Vector2f vector2f0 = Vector2f.UNIT_XY;
      Vector3f vector3f0 = new Vector3f(vector2f0, 1.0F);
      Vector3f vector3f1 = new Vector3f(1.0F, -0.0F, 0.0F);
      boolean boolean0 = vector3f0.equals(vector3f1);
      assertEquals("(1.0, -0.0, 0.0)", vector3f1.toString());
      assertFalse(boolean0);
      assertEquals(1.0F, vector3f0.z, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(3656.4F, (-2122.7F), 0.0F);
      Vector3f vector3f1 = new Vector3f((-3987.0154F));
      Vector3f vector3f2 = vector3f0.UNIT_Z.add(vector3f1);
      boolean boolean0 = vector3f2.equals(vector3f0);
      assertEquals((-2122.7F), vector3f0.y, 0.01F);
      assertEquals("(-3987.0154, -3987.0154, -3986.0154)", vector3f2.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Vector2f vector2f0 = Vector2f.UNIT_XY;
      Vector3f vector3f0 = new Vector3f(vector2f0);
      Vector3f vector3f1 = vector3f0.UNIT_X.divide(vector3f0);
      assertEquals("(1.0, 0.0, NaN)", vector3f1.toString());
      assertEquals("(1.0, 1.0, 0.0)", vector3f0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(3656.4F, (-2122.7F), 0.0F);
      float float0 = vector3f0.getY();
      assertEquals("(3656.4, -2122.7, 0.0)", vector3f0.toString());
      assertEquals((-2122.7F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(3726.4387F);
      float float0 = vector3f0.getZ();
      assertEquals(3726.4387F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f(3726.4387F);
      float float0 = vector3f0.getY();
      assertEquals(3726.4387F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      float float0 = vector3f0.getX();
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f((-3987.0154F));
      float float0 = vector3f0.getX();
      assertEquals((-3987.0154F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Vector2f vector2f0 = Vector2f.UNIT_XY;
      Vector3f vector3f0 = new Vector3f(vector2f0, 1.0F);
      Vector3f vector3f1 = Vector3f.UNIT_Z;
      Vector3f vector3f2 = vector3f0.cross(vector3f1);
      assertEquals("(1.0, -1.0, 0.0)", vector3f2.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Z;
      Vector3f vector3f1 = vector3f0.build(3052.475F);
      Vector3f vector3f2 = vector3f0.cross(vector3f1);
      assertEquals("(-3052.475, 3052.475, 0.0)", vector3f2.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NEGATIVE_INFINITY;
      float[] floatArray0 = new float[6];
      floatArray0[2] = 1219.0F;
      Vector3f vector3f1 = vector3f0.build(floatArray0);
      assertEquals("(0.0, 0.0, 1219.0)", vector3f1.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      Vector3f vector3f1 = vector3f0.build((-285.0F));
      float[] floatArray0 = vector3f1.toArray();
      Vector3f vector3f2 = vector3f0.build(floatArray0);
      assertEquals(3, floatArray0.length);
      assertEquals("(-285.0, -285.0, -285.0)", vector3f2.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      float[] floatArray0 = new float[6];
      floatArray0[1] = Float.NaN;
      Vector3f vector3f1 = vector3f0.build(floatArray0);
      assertEquals("(0.0, NaN, 0.0)", vector3f1.toString());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      float[] floatArray0 = new float[6];
      floatArray0[0] = Float.NaN;
      Vector3f vector3f1 = vector3f0.build(floatArray0);
      assertEquals("(NaN, 0.0, 0.0)", vector3f1.toString());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Vector2f vector2f0 = Vector2f.UNIT_X;
      Vector3f vector3f0 = new Vector3f(vector2f0);
      Vector3f vector3f1 = vector3f0.build(2.0F);
      Vector3f vector3f2 = vector3f1.cross(vector3f0);
      float float0 = vector3f2.getZ();
      assertEquals((-2.0F), float0, 0.01F);
      assertEquals("(0.0, 2.0, -2.0)", vector3f2.toString());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Z;
      Vector3f vector3f1 = vector3f0.build((-1038.0F));
      float float0 = vector3f1.get(1);
      assertEquals((-1038.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NEGATIVE_INFINITY;
      float float0 = vector3f0.angleBetween(vector3f0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Vector2f vector2f0 = Vector2f.UNIT_X;
      Vector3f vector3f0 = new Vector3f(vector2f0);
      float[] floatArray0 = new float[4];
      Vector3f vector3f1 = vector3f0.build(floatArray0);
      float float0 = vector3f1.angleBetween(vector3f1);
      assertEquals("(1.0, 0.0, 0.0)", vector3f0.toString());
      assertEquals(1.5707964F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      // Undeclared exception!
      try { 
        vector3f0.cross((Vector3f) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Z;
      float[] floatArray0 = new float[0];
      // Undeclared exception!
      try { 
        vector3f0.build(floatArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Vector2f vector2f0 = new Vector2f();
      Vector3f vector3f0 = new Vector3f(vector2f0);
      Vector3f vector3f1 = vector3f0.UNIT_X.divide(vector3f0);
      float float0 = vector3f1.get(1);
      assertEquals(Float.NaN, float0, 0.01F);
      assertEquals("(0.0, 0.0, 0.0)", vector3f0.toString());
      assertEquals("(Infinity, NaN, NaN)", vector3f1.toString());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      // Undeclared exception!
      try { 
        vector3f0.get(3);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // index must be either 0, 1 or 2
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      float float0 = vector3f0.get(2);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Z;
      Vector3f vector3f1 = Vector3f.ZERO;
      boolean boolean0 = vector3f1.equals(vector3f0);
      assertFalse(vector3f0.equals((Object)vector3f1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Y;
      Vector3f vector3f1 = Vector3f.ZERO;
      boolean boolean0 = vector3f1.equals(vector3f0);
      assertFalse(vector3f0.equals((Object)vector3f1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NAN;
      Vector3f vector3f1 = vector3f0.cross(vector3f0);
      boolean boolean0 = vector3f0.equals(vector3f1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NAN;
      Vector3f vector3f1 = vector3f0.build(0.0F);
      boolean boolean0 = vector3f0.equals(vector3f1);
      assertFalse(boolean0);
      assertEquals(0.0F, vector3f1.z, 0.01F);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_Z;
      Object object0 = new Object();
      boolean boolean0 = vector3f0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NAN;
      boolean boolean0 = vector3f0.equals(vector3f0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      // Undeclared exception!
      try { 
        vector3f0.angleBetween((Vector3f) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.math.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.UNIT_X;
      Vector3f vector3f1 = vector3f0.cross(vector3f0);
      assertEquals("(0.0, 0.0, 0.0)", vector3f1.toString());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NEGATIVE_INFINITY;
      // Undeclared exception!
      try { 
        vector3f0.build((float[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      float float0 = vector3f0.getX();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Vector3f vector3f0 = null;
      try {
        vector3f0 = new Vector3f((Vector2f) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Vector3f vector3f0 = Vector3f.NAN;
      String string0 = vector3f0.toString();
      assertEquals("(NaN, NaN, NaN)", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Vector3f vector3f0 = null;
      try {
        vector3f0 = new Vector3f((Vector2f) null, 0.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.saintandreas.math.Vector3f", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      float float0 = vector3f0.getY();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Vector3f vector3f0 = new Vector3f();
      float float0 = vector3f0.getZ();
      assertEquals(0.0F, float0, 0.01F);
  }
}
