/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:55:57 GMT 2024
 */

package org.myrobotlab.openni;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.openni.Skeleton;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Skeleton_ESTest extends Skeleton_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Skeleton skeleton0 = new Skeleton();
      assertEquals(0, skeleton0.userId);
  }
}
