/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:07:48 GMT 2024
 */

package org.myrobotlab.net;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.net.Host;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Host_ESTest extends Host_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Host host0 = new Host();
      host0.mac = "qNMau:Eo&]hONvETlO";
      String string0 = host0.toString();
      assertEquals("null null null null", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Host host0 = new Host();
      host0.name = "";
      String string0 = host0.toString();
      assertEquals("null  null null", string0);
  }
}
