/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 05:14:47 GMT 2024
 */

package org.myrobotlab.net;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.net.RouteEntry;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RouteEntry_ESTest extends RouteEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RouteEntry routeEntry0 = new RouteEntry("^O$sE0", "|i0}w,>2Z<M'qX8b", (-1));
      String string0 = routeEntry0.toString();
      assertEquals("id ^O$sE0 uuid |i0}w,>2Z<M'qX8b metric -1", string0);
  }
}
