/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 23:03:09 GMT 2024
 */

package org.myrobotlab.service.data;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.service.data.LedDisplayData;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LedDisplayData_ESTest extends LedDisplayData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LedDisplayData ledDisplayData0 = new LedDisplayData("NL%_O|2!wihg");
      String string0 = ledDisplayData0.toString();
      assertEquals("NL%_O|2!wihg, null", string0);
  }
}
