/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 04:23:05 GMT 2024
 */

package org.myrobotlab.service.data;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.myrobotlab.service.data.OledSsd1306Data;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OledSsd1306Data_ESTest extends OledSsd1306Data_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OledSsd1306Data oledSsd1306Data0 = new OledSsd1306Data();
  }
}
