/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Apr 07 19:05:20 GMT 2024
 */

package org.myrobotlab.logging;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class LoggingSLF4J_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.myrobotlab.logging.LoggingSLF4J"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/iartes/myrobotlab"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(LoggingSLF4J_ESTest_scaffolding.class.getClassLoader() ,
      "org.myrobotlab.logging.LoggingFactory",
      "org.myrobotlab.logging.LoggingSLF4J",
      "org.myrobotlab.logging.Logging",
      "org.myrobotlab.logging.LoggerFactory"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(LoggingSLF4J_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.myrobotlab.logging.LoggerFactory",
      "org.myrobotlab.logging.Logging",
      "org.myrobotlab.logging.LoggingSLF4J",
      "org.myrobotlab.logging.LoggingFactory",
      "org.myrobotlab.framework.Service",
      "org.myrobotlab.service.Pir",
      "org.myrobotlab.framework.MethodCache",
      "org.myrobotlab.framework.MethodCache$MethodIndex",
      "org.myrobotlab.framework.MethodEntry",
      "org.myrobotlab.service.meta.abstracts.MetaData",
      "org.myrobotlab.service.meta.PirMeta",
      "org.myrobotlab.service.config.ServiceConfig",
      "org.myrobotlab.service.config.SpeechRecognizerConfig",
      "org.myrobotlab.service.TestThrower",
      "org.myrobotlab.service.meta.TestThrowerMeta",
      "org.myrobotlab.service.abstracts.AbstractSpeechRecognizer$ListeningEvent",
      "org.myrobotlab.service.interfaces.TextPublisher",
      "org.myrobotlab.service.abstracts.AbstractSpeechRecognizer",
      "org.myrobotlab.service.WebkitSpeechRecognition",
      "org.myrobotlab.service.meta.WebkitSpeechRecognitionMeta",
      "org.myrobotlab.service.Log",
      "org.myrobotlab.service.InMoov2Hand",
      "org.myrobotlab.service.meta.InMoov2HandMeta",
      "org.myrobotlab.document.transformer.Configuration",
      "org.myrobotlab.document.transformer.ConnectorConfig",
      "org.myrobotlab.service.Security",
      "org.myrobotlab.service.IpCamera",
      "org.myrobotlab.service.meta.IpCameraMeta",
      "org.myrobotlab.service.interfaces.MotorControl",
      "org.myrobotlab.service.abstracts.AbstractMotor",
      "org.myrobotlab.service.MotorDualPwm",
      "org.myrobotlab.service.meta.MotorDualPwmMeta",
      "org.myrobotlab.service.abstracts.AbstractServo",
      "org.myrobotlab.service.DiyServo",
      "org.myrobotlab.config.ConfigUtils",
      "org.myrobotlab.service.abstracts.AbstractPinEncoder",
      "org.myrobotlab.service.As5048AEncoder",
      "org.myrobotlab.service.meta.As5048AEncoderMeta",
      "org.myrobotlab.service.meta.SecurityMeta",
      "org.myrobotlab.service.meta.DiyServoMeta",
      "org.myrobotlab.service.interfaces.SpeechSynthesis",
      "org.myrobotlab.service.abstracts.AbstractSpeechSynthesis",
      "org.myrobotlab.service.LocalSpeech",
      "org.myrobotlab.service.meta.abstracts.AbstractSpeechSynthesisMeta",
      "org.myrobotlab.service.meta.LocalSpeechMeta",
      "org.myrobotlab.framework.repo.ServiceDependency",
      "org.myrobotlab.service.Hd44780",
      "org.myrobotlab.service.meta.Hd44780Meta",
      "org.myrobotlab.service.interfaces.SearchPublisher",
      "org.myrobotlab.service.interfaces.ImagePublisher",
      "org.myrobotlab.service.Wikipedia",
      "org.myrobotlab.service.meta.WikipediaMeta",
      "org.myrobotlab.service.config.Hd44780Config",
      "org.myrobotlab.service.config.ClockConfig",
      "org.myrobotlab.service.TestCatcher",
      "org.myrobotlab.service.meta.TestCatcherMeta",
      "com.thoughtworks.xstream.XStream",
      "com.thoughtworks.xstream.io.AbstractDriver",
      "com.thoughtworks.xstream.io.xml.AbstractXmlDriver",
      "com.thoughtworks.xstream.io.xml.StaxDriver",
      "com.thoughtworks.xstream.io.xml.QNameMap",
      "com.thoughtworks.xstream.io.xml.XmlFriendlyNameCoder",
      "com.thoughtworks.xstream.core.JVM$Test",
      "com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider",
      "com.thoughtworks.xstream.converters.reflection.SunLimitedUnsafeReflectionProvider",
      "com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider",
      "com.thoughtworks.xstream.core.util.DependencyInjectionFactory",
      "com.thoughtworks.xstream.converters.reflection.FieldDictionary$DictionaryEntry",
      "com.thoughtworks.xstream.converters.reflection.FieldDictionary",
      "com.thoughtworks.xstream.converters.reflection.ImmutableFieldKeySorter",
      "com.thoughtworks.xstream.converters.reflection.FieldUtil15",
      "com.thoughtworks.xstream.core.util.OrderRetainingMap",
      "com.thoughtworks.xstream.core.util.OrderRetainingMap$ArraySet",
      "com.thoughtworks.xstream.converters.reflection.FieldKey",
      "com.thoughtworks.xstream.core.JVM$1",
      "com.thoughtworks.xstream.core.util.PresortedMap",
      "com.thoughtworks.xstream.core.util.PresortedMap$ArraySet",
      "com.thoughtworks.xstream.core.util.PresortedMap$1",
      "com.thoughtworks.xstream.core.util.PresortedSet",
      "com.thoughtworks.xstream.core.util.CustomObjectOutputStream",
      "com.thoughtworks.xstream.core.util.FastStack",
      "com.thoughtworks.xstream.core.util.Base64JavaUtilCodec",
      "com.thoughtworks.xstream.core.JVM",
      "com.thoughtworks.xstream.core.util.CompositeClassLoader",
      "com.thoughtworks.xstream.core.ClassLoaderReference",
      "com.thoughtworks.xstream.core.DefaultConverterLookup",
      "com.thoughtworks.xstream.core.util.PrioritizedList",
      "com.thoughtworks.xstream.XStream$1",
      "com.thoughtworks.xstream.XStream$2",
      "com.thoughtworks.xstream.mapper.DefaultMapper",
      "com.thoughtworks.xstream.mapper.MapperWrapper",
      "com.thoughtworks.xstream.mapper.DynamicProxyMapper",
      "com.thoughtworks.xstream.mapper.PackageAliasingMapper$1",
      "com.thoughtworks.xstream.mapper.PackageAliasingMapper",
      "com.thoughtworks.xstream.mapper.ClassAliasingMapper",
      "com.thoughtworks.xstream.mapper.ElementIgnoringMapper",
      "com.thoughtworks.xstream.mapper.FieldAliasingMapper",
      "com.thoughtworks.xstream.mapper.AbstractAttributeAliasingMapper",
      "com.thoughtworks.xstream.mapper.AttributeAliasingMapper",
      "com.thoughtworks.xstream.mapper.SystemAttributeAliasingMapper",
      "com.thoughtworks.xstream.mapper.ImplicitCollectionMapper",
      "com.thoughtworks.xstream.mapper.OuterClassMapper",
      "com.thoughtworks.xstream.mapper.ArrayMapper",
      "com.thoughtworks.xstream.mapper.DefaultImplementationsMapper",
      "com.thoughtworks.xstream.mapper.Mapper$Null",
      "com.thoughtworks.xstream.mapper.AttributeMapper",
      "com.thoughtworks.xstream.core.util.CompositeClassLoader$1",
      "com.thoughtworks.xstream.mapper.EnumMapper",
      "com.thoughtworks.xstream.mapper.LocalConversionMapper",
      "com.thoughtworks.xstream.mapper.ImmutableTypesMapper",
      "com.thoughtworks.xstream.mapper.LambdaMapper",
      "com.thoughtworks.xstream.mapper.SecurityMapper",
      "com.thoughtworks.xstream.mapper.AnnotationMapper",
      "com.thoughtworks.xstream.mapper.CachingMapper",
      "com.thoughtworks.xstream.security.NoTypePermission",
      "com.thoughtworks.xstream.security.NullPermission",
      "com.thoughtworks.xstream.security.AnyTypePermission",
      "com.thoughtworks.xstream.security.PrimitiveTypePermission",
      "com.thoughtworks.xstream.security.ArrayTypePermission",
      "com.thoughtworks.xstream.security.InterfaceTypePermission",
      "com.thoughtworks.xstream.security.TypeHierarchyPermission",
      "com.thoughtworks.xstream.security.ExplicitTypePermission",
      "com.thoughtworks.xstream.security.ExplicitTypePermission$1",
      "com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter",
      "com.thoughtworks.xstream.converters.reflection.ReflectionConverter",
      "com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker",
      "com.thoughtworks.xstream.core.util.SerializationMembers$1",
      "com.thoughtworks.xstream.core.util.FastField",
      "com.thoughtworks.xstream.core.util.SerializationMembers",
      "com.thoughtworks.xstream.core.util.PrioritizedList$PrioritizedItem",
      "com.thoughtworks.xstream.converters.reflection.SerializableConverter",
      "com.thoughtworks.xstream.converters.reflection.ReflectionProviderWrapper",
      "com.thoughtworks.xstream.converters.reflection.SerializableConverter$UnserializableParentsReflectionProvider",
      "com.thoughtworks.xstream.converters.reflection.ExternalizableConverter",
      "com.thoughtworks.xstream.converters.basic.NullConverter",
      "com.thoughtworks.xstream.converters.basic.AbstractSingleValueConverter",
      "com.thoughtworks.xstream.converters.basic.IntConverter",
      "com.thoughtworks.xstream.converters.SingleValueConverterWrapper",
      "com.thoughtworks.xstream.converters.basic.FloatConverter",
      "com.thoughtworks.xstream.converters.basic.DoubleConverter",
      "com.thoughtworks.xstream.converters.basic.LongConverter",
      "com.thoughtworks.xstream.converters.basic.ShortConverter",
      "com.thoughtworks.xstream.converters.basic.CharConverter",
      "com.thoughtworks.xstream.converters.basic.BooleanConverter",
      "com.thoughtworks.xstream.converters.basic.ByteConverter",
      "com.thoughtworks.xstream.converters.basic.StringConverter",
      "com.thoughtworks.xstream.core.util.WeakCache",
      "com.thoughtworks.xstream.converters.basic.StringBufferConverter",
      "com.thoughtworks.xstream.converters.basic.DateConverter",
      "com.thoughtworks.xstream.core.util.ThreadSafeSimpleDateFormat",
      "com.thoughtworks.xstream.core.util.Pool",
      "com.thoughtworks.xstream.core.util.ThreadSafeSimpleDateFormat$1",
      "com.thoughtworks.xstream.converters.collections.BitSetConverter",
      "com.thoughtworks.xstream.converters.basic.URIConverter",
      "com.thoughtworks.xstream.converters.basic.URLConverter",
      "com.thoughtworks.xstream.converters.basic.BigIntegerConverter",
      "com.thoughtworks.xstream.converters.basic.BigDecimalConverter",
      "com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter",
      "com.thoughtworks.xstream.converters.collections.ArrayConverter",
      "com.thoughtworks.xstream.converters.collections.CharArrayConverter",
      "com.thoughtworks.xstream.converters.collections.CollectionConverter",
      "com.thoughtworks.xstream.converters.collections.MapConverter",
      "com.thoughtworks.xstream.converters.collections.TreeMapConverter$NullComparator",
      "com.thoughtworks.xstream.converters.collections.TreeMapConverter",
      "com.thoughtworks.xstream.converters.collections.TreeSetConverter",
      "com.thoughtworks.xstream.converters.collections.TreeSetConverter$1",
      "com.thoughtworks.xstream.converters.collections.SingletonCollectionConverter",
      "com.thoughtworks.xstream.converters.collections.SingletonMapConverter",
      "com.thoughtworks.xstream.converters.collections.PropertiesConverter",
      "com.thoughtworks.xstream.converters.extended.EncodedByteArrayConverter",
      "com.thoughtworks.xstream.converters.extended.FileConverter",
      "com.thoughtworks.xstream.converters.extended.SqlTimestampConverter",
      "com.thoughtworks.xstream.converters.extended.SqlTimeConverter",
      "com.thoughtworks.xstream.converters.extended.SqlDateConverter",
      "com.thoughtworks.xstream.converters.extended.DynamicProxyConverter",
      "com.thoughtworks.xstream.converters.extended.JavaClassConverter",
      "com.thoughtworks.xstream.converters.extended.JavaMethodConverter",
      "com.thoughtworks.xstream.converters.extended.JavaFieldConverter",
      "com.thoughtworks.xstream.converters.extended.FontConverter",
      "com.thoughtworks.xstream.converters.reflection.AbstractAttributedCharacterIteratorAttributeConverter",
      "com.thoughtworks.xstream.converters.extended.TextAttributeConverter",
      "com.thoughtworks.xstream.converters.extended.ColorConverter",
      "com.thoughtworks.xstream.converters.extended.LookAndFeelConverter",
      "com.thoughtworks.xstream.converters.extended.LocaleConverter",
      "com.thoughtworks.xstream.converters.extended.GregorianCalendarConverter",
      "com.thoughtworks.xstream.converters.extended.SubjectConverter",
      "com.thoughtworks.xstream.converters.extended.ThrowableConverter",
      "com.thoughtworks.xstream.converters.extended.StackTraceElementFactory",
      "com.thoughtworks.xstream.converters.extended.StackTraceElementFactory15",
      "com.thoughtworks.xstream.converters.extended.StackTraceElementConverter",
      "com.thoughtworks.xstream.converters.extended.CurrencyConverter",
      "com.thoughtworks.xstream.converters.extended.RegexPatternConverter",
      "com.thoughtworks.xstream.converters.extended.CharsetConverter",
      "com.thoughtworks.xstream.converters.extended.DurationConverter",
      "com.thoughtworks.xstream.converters.extended.DurationConverter$1",
      "com.thoughtworks.xstream.converters.enums.EnumConverter",
      "com.thoughtworks.xstream.converters.enums.EnumSetConverter",
      "com.thoughtworks.xstream.converters.enums.EnumMapConverter",
      "com.thoughtworks.xstream.converters.basic.StringBuilderConverter",
      "com.thoughtworks.xstream.converters.basic.UUIDConverter",
      "com.thoughtworks.xstream.converters.extended.ActivationDataFlavorConverter",
      "com.thoughtworks.xstream.converters.extended.PathConverter",
      "com.thoughtworks.xstream.converters.time.ChronologyConverter",
      "com.thoughtworks.xstream.converters.time.DurationConverter",
      "com.thoughtworks.xstream.converters.time.AbstractChronoLocalDateConverter",
      "com.thoughtworks.xstream.converters.time.HijrahDateConverter",
      "com.thoughtworks.xstream.converters.time.JapaneseDateConverter",
      "com.thoughtworks.xstream.converters.time.JapaneseEraConverter",
      "com.thoughtworks.xstream.converters.time.InstantConverter",
      "com.thoughtworks.xstream.converters.time.LocalDateConverter",
      "com.thoughtworks.xstream.converters.time.LocalDateTimeConverter",
      "com.thoughtworks.xstream.converters.time.LocalTimeConverter",
      "com.thoughtworks.xstream.converters.time.MinguoDateConverter",
      "com.thoughtworks.xstream.converters.time.MonthDayConverter",
      "com.thoughtworks.xstream.converters.time.OffsetDateTimeConverter",
      "com.thoughtworks.xstream.converters.time.OffsetTimeConverter",
      "com.thoughtworks.xstream.converters.time.PeriodConverter",
      "com.thoughtworks.xstream.converters.time.SystemClockConverter",
      "com.thoughtworks.xstream.converters.time.ThaiBuddhistDateConverter",
      "com.thoughtworks.xstream.converters.time.ValueRangeConverter",
      "com.thoughtworks.xstream.converters.time.WeekFieldsConverter",
      "com.thoughtworks.xstream.converters.time.YearConverter",
      "com.thoughtworks.xstream.converters.time.YearMonthConverter",
      "com.thoughtworks.xstream.converters.time.ZonedDateTimeConverter",
      "com.thoughtworks.xstream.converters.time.ZoneIdConverter",
      "com.thoughtworks.xstream.converters.reflection.LambdaConverter",
      "com.thoughtworks.xstream.core.util.SelfStreamingInstanceChecker",
      "com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy",
      "com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategy",
      "org.myrobotlab.service.ThingSpeak",
      "org.myrobotlab.service.meta.ThingSpeakMeta",
      "org.myrobotlab.service.config.ServoConfig",
      "org.myrobotlab.service.meta.LogMeta",
      "com.thoughtworks.xstream.io.AbstractReader",
      "com.thoughtworks.xstream.io.xml.AbstractXmlReader",
      "com.thoughtworks.xstream.io.xml.AbstractPullReader",
      "com.thoughtworks.xstream.io.xml.StaxReader",
      "com.thoughtworks.xstream.core.util.Cloneables",
      "com.thoughtworks.xstream.io.xml.AbstractPullReader$Event",
      "com.thoughtworks.xstream.core.BaseException",
      "com.thoughtworks.xstream.XStreamException",
      "com.thoughtworks.xstream.io.StreamException",
      "org.myrobotlab.service.OpenNi",
      "org.myrobotlab.service.meta.OpenNiMeta",
      "org.myrobotlab.service.Bno055",
      "org.myrobotlab.service.meta.Bno055Meta",
      "org.myrobotlab.service.InMoov2Torso",
      "org.myrobotlab.service.meta.InMoov2TorsoMeta",
      "org.myrobotlab.service.Maven",
      "org.myrobotlab.service.meta.MavenMeta",
      "org.myrobotlab.service.InMoov2Arm",
      "org.myrobotlab.service.meta.InMoov2ArmMeta",
      "org.myrobotlab.service.InMoov2Head",
      "org.myrobotlab.service.meta.InMoov2HeadMeta",
      "org.myrobotlab.service.Cron",
      "org.myrobotlab.service.meta.CronMeta",
      "org.myrobotlab.service.Clock",
      "org.myrobotlab.service.meta.ClockMeta",
      "org.myrobotlab.service.Lm75a",
      "org.myrobotlab.service.meta.Lm75aMeta",
      "org.myrobotlab.serial.Port",
      "org.myrobotlab.serial.PortQueue",
      "org.myrobotlab.framework.QueueStats",
      "org.myrobotlab.service.Gps",
      "org.myrobotlab.service.meta.GpsMeta",
      "org.myrobotlab.service.ServoMixer",
      "org.myrobotlab.service.meta.ServoMixerMeta",
      "org.myrobotlab.service.Serial",
      "org.myrobotlab.service.Lidar",
      "org.myrobotlab.service.meta.LidarMeta",
      "org.myrobotlab.sensor.TimeEncoder",
      "org.myrobotlab.framework.Plan",
      "org.myrobotlab.service.config.RuntimeConfig",
      "org.myrobotlab.framework.NameGenerator",
      "org.myrobotlab.service.data.Locale",
      "org.myrobotlab.service.WatchDogTimer",
      "org.myrobotlab.service.meta.WatchDogTimerMeta",
      "org.myrobotlab.service.Servo",
      "org.myrobotlab.service.meta.ServoMeta",
      "org.myrobotlab.service.abstracts.AbstractMotorController",
      "org.myrobotlab.service.RoboClaw",
      "org.myrobotlab.service.meta.RoboClawMeta",
      "org.myrobotlab.service.Pcf8574",
      "org.myrobotlab.service.meta.Pcf8574Meta",
      "org.myrobotlab.service.SensorMonitor",
      "org.myrobotlab.service.meta.SensorMonitorMeta",
      "org.myrobotlab.service.WolframAlpha",
      "org.myrobotlab.service.meta.WolframAlphaMeta"
    );
  }
}
